FROM ubuntu:20.04

WORKDIR /app

COPY . /app

RUN apt update -y && apt install -y python3 python3-pip && pip install --upgrade pip

RUN pip install -r backend/requirements.txt

EXPOSE 8000

ENTRYPOINT ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
